language: python

python:
  - 2.7
  - 3.3
  - 3.4

# Master is different that 1.7 RC1
env:
  - DJANGO=https://github.com/django/django/tarball/master
  - DJANGO=https://www.djangoproject.com/download/1.7c1/tarball/
  - DJANGO=Django==1.6.5
  - DJANGO=Django==1.5.8

install:
  - pip install flake8 coverage coveralls
  - pip install -e .
  - pip install $DJANGO

script:
  - flake8 --max-line-length=100 --max-complexity=10 --statistics --benchmark forums
  - coverage run setup.py test
  - coverage report

after_success: coveralls
