language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO=https://github.com/django/django/tarball/master
  - DJANGO=Django==1.7.1
  - DJANGO=Django==1.6.8
  - DJANGO=Django==1.5.11

install:
  - pip install flake8 coverage coveralls
  - pip install -e .
  - pip install $DJANGO

script:
  - flake8 --max-line-length=100 --max-complexity=10 --statistics --benchmark forums
  - coverage run setup.py test
  - coverage report

after_success: coveralls
